### PR TITLE
Resolve core.hooksPath relative to GIT_WORK_TREE

### LINKED ISSUE #2281: Pre-commit hooks are executed only when launched from the git root
**Describe the bug**
Pre-commit hook is ignored.

**To Reproduce**
1. `mkdir .githooks && git config --local core.hooksPath .githooks`
2. Create `.githooks/pre-commit` with `echo "Hook triggered" && exit 1` and `chmod +x` it.
3. `git commit` now fails, as expected.
4. `gitui` ignores the hook.

**Expected behavior**
`pre-commit` behaviour is the same when using `git` CLI.

**Screenshots**
N/A.

**Context (please complete the following information):**
 - OS/Distro + Version: `Debian 12`
 - GitUI Version: `gitui 0.25.2`
 - Rust version: `rustc 1.76.0`

**Additional context**
Relates to:
- https://github.com/extrawurst/gitui/pull/1054
- (maybe) https://github.com/extrawurst/gitui/issues/1711

### PR DESCRIPTION
**Pull request by naseschwarz**
git supports a relative path in core.hooksPath.

`man git-config`:

> A relative path is taken as relative to the directory where the hooks are
> run (see the "DESCRIPTION" section of githooks[5]).

`man githooks`:

> Before Git invokes a hook, it changes its working directory to either
> $GIT_DIR in a bare repository or the root of the working tree in a >
> non-bare repository.

I.e. relative paths in core.hooksPath in non-bare repositories are always relative to GIT_WORK_TREE.

There is a further exception; I believe this is not considered for path resolution:

> An exception are hooks triggered during a push (pre-receive, update,
> post-receive, post-update, push-to-checkout) which are always executed
> in $GIT_DIR.

This Pull Request fixes/closes #2281.

It changes the following:
- Synchronizes core.hooksPath resolution with the git command line client

I followed the checklist:
- [x] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

### CODE REVIEW

File: git2-hooks/src/lib.rs [hunk 1]
```diff
@@ -98,7 +98,11 @@ pub fn create_hook(
 	path
 }
 
-fn create_hook_in_path(path: &Path, hook_script: &[u8]) {
+/// helper method to create a git hook in a custom path (used in unittests)
+///
+/// # Panics
+/// Panics if hook could not be created
+pub fn create_hook_in_path(path: &Path, hook_script: &[u8]) {
```
Comment (extrawurst) [inline git2-hooks/src/lib.rs:105]: If we just want this to be for testing, we might want to consider feature gating it so it does not become public api which would make it semver breaking to change

Comment (naseschwarz) [reply git2-hooks/src/lib.rs]: I agree, `git2_hooks::create_hook` already has the same problem.

I've moved `git2_hooks::create_hook_in_path` into `git2-testing`. I've also moved `git2_hooks::create_hook` into a private mod and publish it via `git2_hooks::test_utils::crate_hook` only if the `test-utils` feature flag is set. (I can't move `create_hook` to `git2-testing`, as it has a dependency on "`HookPaths`".)

I'm open to as simpler and cleaner solution. Having this feature flag and the function in test_utils makes this a bit more explicit, but this is of course never tested or even built if all tests on this are run in this workspace with the flag enabled.

Comment (naseschwarz) [reply git2-hooks/src/lib.rs]: If you want to deal with this discussion separately, I can easily move this into a separate PR by the way.

File: asyncgit/Cargo.toml [hunk 2]
```diff
@@ -18,7 +18,7 @@ dirs = "5.0"
 easy-cast = "0.5"
 fuzzy-matcher = "0.3"
 git2 = "0.20"
-git2-hooks = { path = "../git2-hooks", version = ">=0.4" }
+git2-hooks = { path = "../git2-hooks", version = ">=0.4", features = ["test-utils"] }
```
Comment (extrawurst) [inline asyncgit/Cargo.toml:21]: wait this means we will always use its test-utils feature, not just for test-runs? is that intended?

**Comment by extrawurst** [comment]
@Byron this might affect Gitbutler. Would love your pair of eyes

File: asyncgit/Cargo.toml (hunk 2 above)
Comment (naseschwarz) [reply asyncgit/Cargo.toml:21]: Yes. Do you prefer to set this feature flags only for tests?

We then have to always run tests with that feature flag and propagate it from the toplevel crate to git2-hooks. For gitui this is fine, as there's a request for running `make check` in the PR template. It may impede developers who just mechanically run `cargo test --workspace`, unless there is a way to enable a feature flags just for tests, which I don't believe there is.

I assumed enabling it for the workspace was okay, as your concern was semver breaking changes and dependencies are fixed within the gitui workspace. The way this is organized right now is not worse than before, at least, with semver concerns alleviated.

Thank you for looking at this.

Comment (naseschwarz) [reply asyncgit/Cargo.toml:21]: That being said, maybe we should just copy/paste the function to asyncgit for tests and don't waste time on discussing or publishing a random feature flag that sounds fishy.

Comment (extrawurst) [reply asyncgit/Cargo.toml:21]: yeah let’s do that 👍 simple and pragmatic

File: asyncgit/src/sync/hooks.rs [hunk 3]
```diff
@@ -174,4 +191,37 @@ mod tests {
 
 		assert_eq!(msg, String::from("msg\n"));
 	}
+
+	#[test]
+	fn test_hooks_commit_msg_reject_in_hooks_folder_githooks_moved_absolute(
+	) {
+		let (_td, repo) = repo_init().unwrap();
+		let root = repo.path().parent().unwrap();
```
Comment (Byron) [inline asyncgit/src/sync/hooks.rs:199]: `repo.workdir()` should rather be used here.

**Review by Byron — COMMENTED** [review]
Thanks for calling me in @extrawurst , and thanks @naseschwarz for tackling this!

I'd arrive at the same conclusion on how the implementation should look like, and it's great to see all the right tests.

Of course, I'd have a few nits but they are not material.

It's worth noting that `core.hooksPath` is very relevant to security on shared drives in particular, and since `git2` follows Git and will refuse to open such repositories it should be safe to use `core.hooksPath` here. In `gitoxide` one would use [`trusted_path()`](https://docs.rs/gix/latest/gix/config/struct.Snapshot.html#method.trusted_path) instead to obtain the fully-interpolated path if it's in a trusted configuration file.

**Comment by naseschwarz** [comment]
Thank you for your time and input, @Byron.

**Comment by extrawurst** [comment]
Thank you!

**Comment by Byron** [comment]
Would it be possible to have a release for this?

If there is a different schedule, I am OK to use `git2-hooks` as Git dependency as well, but thought I could ask first 😅.

**Comment by extrawurst** [comment]
@Byron we should probably move this into its own repo to simplify visibility and separate release schedule. will cut a release now

**Comment by extrawurst** [comment]
@Byron released as git2-hooks `0.5.0`
