### PR TITLE
Push with refspec

### LINKED ISSUE #2537: Failure to follow config push settings
**Describe the bug**
I'm working on a repo with multiple remotes (origin and fork) and have a branch locally with different name which pushes to `main` branch on the fork

**To Reproduce**
1. set upstream of a branch to a differently named one:
`.git/config`
```
[branch "lints"]
	remote = workspace-lints
	merge = refs/heads/main
```
2. set default for push to upstream (without it the cli asks you to specify to which branch)
in `.git/config`
```
[push]
    default = upstream
```
3. prepare a commit and push with gitui
4. gitui creates a branch with the name of the local branch and pushes to it

**Expected behavior**
when executing `git push --verbose` on such branch
```
Pushing to gitlab.torproject.org:matt022/workspace-lints
To gitlab.torproject.org:matt022/workspace-lints
 = [up to date]          lints -> main
updating local tracking ref 'refs/remotes/workspace-lints/main'
Everything up-to-date
```

**Screenshots**
N/A

**Context (please complete the following information):**
Rust: cargo 1.84.0 (66221abde 2024-11-19) (stable)
gitui: 0.27.0
OS: NixOS 25.05 (Warbler) x86_64
Host: Windows Subsystem for Linux - NixOS (2.4.11)
Kernel: Linux 5.15.167.4-microsoft-standard-WSL2
Shell: bash 5.2.37

**Additional context**
As noted in the logs this is a gitlab instance if that changes things

### PR DESCRIPTION
**Pull request by vlad-anger**
Fixes #2537

git2 merged [necessary PR](https://github.com/rust-lang/git2-rs/pull/1131)

This PR _is_blocked_ until new version git2 lib released
For now use git2 from master to be able to test PR.

---

Assume git config:
```git-config
[branch "oblava"]
	remote = origin
	merge = refs/heads/master
[push]
  default = upstream
```
Prev. behavior:
push -> push oblava -> remote oblava <- new remote created

New behavior:
push -> push oblava -> remote master

---

I followed the checklist:
- [x] I added unittests
- [x] I ran `make check` without errors (see commit with tests fixes)
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

### CODE REVIEW

**Review by naseschwarz — CHANGES_REQUESTED** [review]
Just for completeness, I'll add a reference to our discussion @vlad-anger. Thank you for the productive discussion!

In #2537 we discussed that the new behavior should be conditional on the value of `push.default`: Only if `push.default == upstream`, `merge.*.branch` is used as the remote branch.

**Comment by cruessler** [comment]
Just to make sure I get the context right: does any of this require changes to https://github.com/gitui-org/gitui/blob/35b2529c52d601d9640530c55c3805e3a9882fea/asyncgit/src/sync/remotes/mod.rs#L133-L233? Or is that not the case as this PR deals with branches while the code I linked to deals with remotes?

**Comment by vlad-anger** [comment]
> Or is that not the case as this PR deals with branches while the code I linked to deals with remotes?

Yeah those helpers out of scope, they tell which remote can be used,
while this PR is fixing different local/remote _branches_ issue,

Ex. locally i have branch t1, which should be pushed to remote t2.
To achieve that, you could have `push.default=upstream` &
`branch.t1.merge=refs/heads/t2`
For now gitui will try to push t1 -> t1 always

**Comment by vlad-anger** [comment]
Tweaked logic, updated PR desc.
Waiting for upstream version release, so CI build won't fail and we
can do final checks

File: asyncgit/src/sync/remotes/push.rs [hunk 1]
```diff
@@ -163,9 +171,23 @@ pub fn push_raw(
 		PushType::Tag => "tags",
 	};
 
-	let branch_name =
+	let mut push_ref =
 		format!("{branch_modifier}refs/{ref_type}/{branch}");
-	remote.push(&[branch_name.as_str()], Some(&mut options))?;
+
+	if !delete
+		&& matches!(
```
Comment (naseschwarz) [inline asyncgit/src/sync/remotes/push.rs:178]: Is there a reason to use `matches!` unless you want to do pattern matching? Shouldn't this be a simple equality?

File: asyncgit/src/sync/config.rs [hunk 2]
```diff
@@ -62,6 +62,54 @@ pub fn untracked_files_config_repo(
...
+pub fn push_default_strategy_config_repo(
+	repo: &Repository,
+) -> Result<PushDefaultStrategyConfig> {
+	(get_config_string_repo(repo, "push.default")?).map_or_else(
+		|| Ok(PushDefaultStrategyConfig::default()),
+		|entry_str| {
+			Ok(PushDefaultStrategyConfig::try_from(
+				entry_str.as_str(),
+			)
+			.unwrap_or_default())
```
Comment (naseschwarz) [inline asyncgit/src/sync/config.rs:108]: Just a note: The behavior of the git command line client is to reject a push if the value of push.default is defined but not valid.

```
% git -c push.default=snerflop push origin HEAD
error: malformed value for push.default: snerflop
error: must be one of nothing, matching, simple, upstream or current
fatal: unable to parse 'push.default' from command-line config
128 %
```

Doing this might come in handy in case `git` adds new options in the future, which gitui does not support, so we don't accidentally implement incorrect push behavior.

File: asyncgit/src/sync/remotes/push.rs [hunk 3]
```diff
@@ -163,9 +171,23 @@ pub fn push_raw(
...
+			push_default_strategy,
+			PushDefaultStrategyConfig::Upstream
+		) {
```
Comment (naseschwarz) [inline asyncgit/src/sync/remotes/push.rs:181]: The way `push_ref` is constructed leads me to believe that this code is also used to push tags, but `branch.*.merge` should only be applied to branches, right? Thus, this condition should probably be extended by `&& ref_type == PushType::Branch`.

File: asyncgit/src/sync/config.rs [hunk 4]
```diff
@@ -62,6 +62,54 @@ pub fn untracked_files_config_repo(
...
+	fn try_from(
+		value: &'a str,
+	) -> std::result::Result<Self, Self::Error> {
+		match value {
+			"nothing" => Ok(Self::Nothing),
+			"current" => Ok(Self::Current),
+			"upstream" => Ok(Self::Upstream),
+			"simple" => Ok(Self::Simple),
+			"matching" => Ok(Self::Matching),
+			_ => Err(crate::Error::Generic(format!(
```
Comment (naseschwarz) [inline asyncgit/src/sync/config.rs:92]: May I suggest to introduce a new error type, like `Error::GitConfig`? We could add the offending configuration key and maybe provide slightly nicer error messages in gitui.

File: asyncgit/src/sync/branch/mod.rs [hunk 5]
```diff
@@ -243,6 +243,25 @@ pub fn get_branch_remote(
 	}
 }
 
+/// Retrieve the upstream merge of a local `branch`,
+/// configured in "branch.*.merge"
+/// 
+/// For details check git2 `branch_upstream_merge`
+pub fn get_branch_upstream_merge(
```
Comment (naseschwarz) [inline asyncgit/src/sync/branch/mod.rs:250]: `asyncgit/src/sync/branch/mod.rs` seems to have rather good test coverage. Would it be reasonable to add one for `get_branch_upstream_merge`?

File: asyncgit/src/sync/config.rs [hunk 6]
```diff
@@ -62,6 +62,54 @@ pub fn untracked_files_config_repo(
 	Ok(ShowUntrackedFilesConfig::All)
 }
 
+// see https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushdefault
+/// represent `push.default` git config
```
Comment (naseschwarz) [inline asyncgit/src/sync/config.rs:66]:
```suggestion
/// represents `push.default` git config
```

File: asyncgit/src/sync/config.rs [hunk 7]
```diff
@@ -62,6 +62,54 @@ pub fn untracked_files_config_repo(
...
+		value: &'a str,
+	) -> std::result::Result<Self, Self::Error> {
+		match value {
+			"nothing" => Ok(Self::Nothing),
+			"current" => Ok(Self::Current),
+			"upstream" => Ok(Self::Upstream),
+			"simple" => Ok(Self::Simple),
+			"matching" => Ok(Self::Matching),
+			_ => Err(crate::Error::Generic(format!(
+				"{value} is incorrect push.default"
```
Comment (naseschwarz) [inline asyncgit/src/sync/config.rs:93]: Let's steal the error message from git. This makes it easier for users to find a solution.

```suggestion
				"malformed value for push.default: {value}, must be one of nothing, matching, simple, upstream or current"
```

**Review by naseschwarz — COMMENTED** [review]
Thank you very much for addressing my concerns. :+1: 

Here are some thoughts on the current version.

**Comment by naseschwarz** [comment]
Apart from the review item regarding pushing tags, I believe the push logic in this version is correctly aligned with git for `push.default` in {`upstream`, `simple`}.

`matching` and `upstream` are options that, as far as I can tell, fall back to `simple` in case a push source is given, which I assume is always the case in `push_raw` (unless delete is true, in which case only a destination is used). Thus, I'd agree that the implementation covers these correctly, too. It might be worth making this explicit so that devs keep this in mind when working on `push_raw`, e.g. by actually explicitly writing `match` on `push_default_strategy` and adding a short remark in the branch that does nothing.

File: asyncgit/src/sync/remotes/push.rs (hunk 1 above)
Comment (extrawurst) [reply asyncgit/src/sync/remotes/push.rs:178]: Yeah lets make it derive `PartialEq` and then its a simple `==`

Comment (vlad-anger) [reply asyncgit/src/sync/remotes/push.rs]: ok

File: asyncgit/src/sync/config.rs (hunk 2 above)
Comment (vlad-anger) [reply asyncgit/src/sync/config.rs]: Good point. Now we'll fall with normal err
image

File: asyncgit/src/sync/config.rs (hunk 4 above)
Comment (vlad-anger) [reply asyncgit/src/sync/config.rs]: It's here. I've made it's string, cause not sure that kind of error will _always_ be with config key entry

File: asyncgit/src/sync/branch/mod.rs (hunk 5 above)
Comment (vlad-anger) [reply asyncgit/src/sync/branch/mod.rs:250]: Added

File: asyncgit/src/sync/config.rs (hunk 6 above)
Comment (vlad-anger) [reply asyncgit/src/sync/config.rs]: haha

File: asyncgit/src/sync/config.rs (hunk 7 above)
Comment (vlad-anger) [reply asyncgit/src/sync/config.rs]: Good point, like it!

File: asyncgit/src/sync/config.rs [hunk 8]
```diff
@@ -62,6 +62,54 @@ pub fn untracked_files_config_repo(
...
+
+impl<'a> TryFrom<&'a str> for PushDefaultStrategyConfig {
+	type Error = crate::Error;
+	fn try_from(
+		value: &'a str,
+	) -> std::result::Result<Self, Self::Error> {
+		match value {
+			"nothing" => Ok(Self::Nothing),
+			"current" => Ok(Self::Current),
+			"upstream" => Ok(Self::Upstream),
```
[the remark this answers is not in the document]
Comment (vlad-anger) [reply asyncgit/src/sync/config.rs]: Ja it's legacy but let's support

**Comment by vlad-anger** [comment]
@naseschwarz I liked first review round, let's go for another one!

**Review by naseschwarz — APPROVED** [review]
I've tested this against the git2@d1ae3b6c2d1200e7d82468af447fa66259225ecf and it works as I would have expected. A push in `gitui` now behaves like a `git push <push default> $(git rev-parse --abbrev-ref HEAD)` in the terminal.

There's only one small formatting remark.

**Comment by naseschwarz** [comment]
There has been a git2 release, upgrade and patch in #2567! :)

File: asyncgit/src/error.rs [hunk 9]
```diff
@@ -53,6 +53,10 @@ pub enum Error {
 	#[error("git error:{0}")]
 	Git(#[from] git2::Error),
 
+	///
+	#[error("git config error:{0}")]
```
[the remark this answers is not in the document]
Comment (vlad-anger) [reply asyncgit/src/error.rs]: Yeap

**Review by naseschwarz — CHANGES_REQUESTED** [review]
Hey @vlad-anger. Please excuse me missing this in the previous two rounds, but I have one more request: Would you please add an entry to CHANGELOG.md?

**Comment by vlad-anger** [comment]
Yeap added changelog. Rebased on top of master

**Comment by vlad-anger** [comment]
@naseschwarz Thanks for reviewing! :)

**Review by naseschwarz — APPROVED** [review]
