### PR TITLE
Disable dotted range commit yanking

### LINKED ISSUE #2576: Copying multiple hashes yields incorrect dotted range on nonlinear histories and consecutive selections
**Describe the bug**
Copying multiple hashes that are consecutive in the gitui revlog display yields incorrect dotted range if the commit history is not linear.

**To Reproduce**

1. Build a test graph:
```
git init
touch a
git add -A
git commit -m 'a'
touch b
git add -A
git commit -m 'b'
git checkout HEAD~ -b c
touch c
git add -A
git commit -m 'c'
git checkout -
git merge --no-ff c
```
3. Start gitui
4. Switch to Log [2]
5. Select commit with message 'c'
6. Press space
7. Select commit with message 'b'
8. Press space
9. Press y to yank commits
10. On the result, run `get rev-list '<copied text here>'`
11. git rev-list only outputs one commit

**Expected behavior**
`git rev-list` lists the two selected commits 

**Screenshots**
Constructed history:

Image

Revlog with selection

Image

Yanked commit sequence and rev-list output

Image

**Context (please complete the following information):**
 - OS/Distro + Version: Linux 6.13.6
 - GitUI Version 0.27
 - Rust version: 1.85

### PR DESCRIPTION
**Pull request by naseschwarz**
The algorithm for computing marked_consecutive assumes that commits are consecutive in the commit graph if they are consecutive in the linearized log used in` commitlist.rs`. That is not universally correct, as siblings may also be displayed consecutively in this list.

For now, this just removes generating commit lists in dotted range notation.

This Pull Request fixes/closes #2576 

It changes the following:
- Removes dotted range notation commit yanking

I followed the checklist:
- [x] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by extrawurst** [comment]
@naseschwarz this could be unattested, right?

**Comment by naseschwarz** [comment]
@vlad-anger: I'll add some test to this and give you a heads up. No need to look at this right now.

**Comment by naseschwarz** [comment]
@vlad-anger: Here we go. :)

File: src/components/commitlist.rs [hunk 1]
```diff
@@ -916,4 +938,127 @@ mod tests {
...
+		// 0000000000000000000000000000000000000001
+		// 0000000000000000000000000000000000000002
+		// ...
+		items.set_items(
+			2, /* randomly choose an offset */
+			(0..20)
+				.map(|idx| CommitInfo {
+					id: CommitId::from_str_unchecked(&format!(
+						"{:040}",
+						idx
```
Comment (vlad-anger) [inline src/components/commitlist.rs:962]:
```suggestion
						"{idx:040}",
```

File: src/components/commitlist.rs [hunk 2]
```diff
@@ -916,4 +938,127 @@ mod tests {
...
+					))
+					.unwrap(),
+					..basic_commit_info.clone()
+				})
+				.collect(),
+			None,
+		);
+		CommitList {
+			items: items,
```
Comment (vlad-anger) [inline src/components/commitlist.rs:971]:
```suggestion
			items,
```

File: src/components/commitlist.rs [hunk 3]
```diff
@@ -916,4 +938,127 @@ mod tests {
...
+				"0000000000000000000000000000000000000002"
+			))
+		);
+	}
+
+	#[test]
+	fn test_copy_commit_one_marked() {
+		let cl = build_commit_list_with_some_commits();
+		let cl = CommitList {
+			marked: build_marked_from_indices(&cl, &vec![3]),
```
Comment (vlad-anger) [inline src/components/commitlist.rs:1020]:
```suggestion
			marked: build_marked_from_indices(&cl, &[3]),
```

File: src/components/commitlist.rs [hunk 4]
```diff
@@ -916,4 +938,127 @@ mod tests {
...
+				"0000000000000000000000000000000000000001",
+			))
+		);
+	}
+
+	#[test]
+	fn test_copy_commit_range_marked() {
+		let cl = build_commit_list_with_some_commits();
+		let cl = CommitList {
+			marked: build_marked_from_indices(&cl, &vec![4, 5, 6, 7]),
```
Comment (vlad-anger) [inline src/components/commitlist.rs:1035]:
```suggestion
			marked: build_marked_from_indices(&cl, &[4, 5, 6, 7]),
```

File: src/components/commitlist.rs [hunk 5]
```diff
@@ -916,4 +938,127 @@ mod tests {
...
+				"0000000000000000000000000000000000000005"
+			)))
+		);
+	}
+
+	#[test]
+	fn test_copy_commit_random_marked() {
+		let cl = build_commit_list_with_some_commits();
+		let cl = CommitList {
+			marked: build_marked_from_indices(&cl, &vec![4, 7]),
```
Comment (vlad-anger) [inline src/components/commitlist.rs:1053]:
```suggestion
			marked: build_marked_from_indices(&cl, &[4, 7]),
```

**Review by vlad-anger — COMMENTED** [review]
I've checked PR & see why implemented dotted yank was not sufficient.
Should we add some notes/todos for future implementors?
Also my 2 review cents:

**Comment by naseschwarz** [comment]
Thank you, @vlad-anger. I've applied all suggestions.

**Comment by extrawurst** [comment]
Awesome !
